---
version: '2.1'
services:
  kafka-4:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 4
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: ${ZK_O_HOSTNAME}:12181,${ZK_O_HOSTNAME}:22181,${ZK_O_HOSTNAME}:32181,${HOSTNAME}:42181,${HOSTNAME}:52181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://${HOSTNAME}:49092,EXTERNAL://${PUBLIC_IP}:49093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_DELETE_RETENTION_MS: 1000
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
  kafka-5:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 5
      KAFKA_ZOOKEEPER_CONNECT: ${ZK_O_HOSTNAME}:12181,${ZK_O_HOSTNAME}:22181,${ZK_O_HOSTNAME}:32181,${HOSTNAME}:42181,${HOSTNAME}:52181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://${HOSTNAME}:59092,EXTERNAL://${PUBLIC_IP}:59093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_DELETE_RETENTION_MS: 1000
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
