---
version: '2.1'
services:
  kafka-1:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: ${HOSTNAME}:12181,${HOSTNAME}:22181,${HOSTNAME}:32181,${ZK_O_HOSTNAME}:42181,${ZK_O_HOSTNAME}:52181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://${HOSTNAME}:19092,EXTERNAL://${PUBLIC_IP}:19093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_DELETE_RETENTION_MS: 1000
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_ERRORS_TOLERANCE: "all"
      KAFKA_ERRORS_DEADLETTERQUEUE_TOPIC_NAME: "dead"
  kafka-2:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: ${HOSTNAME}:12181,${HOSTNAME}:22181,${HOSTNAME}:32181,${ZK_O_HOSTNAME}:42181,${ZK_O_HOSTNAME}:52181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://${HOSTNAME}:29092,EXTERNAL://${PUBLIC_IP}:29093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_DELETE_RETENTION_MS: 1000
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_ERRORS_TOLERANCE: "all"
      KAFKA_ERRORS_DEADLETTERQUEUE_TOPIC_NAME: "dead"
  kafka-3:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: ${HOSTNAME}:12181,${HOSTNAME}:22181,${HOSTNAME}:32181,${ZK_O_HOSTNAME}:42181,${ZK_O_HOSTNAME}:52181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://${HOSTNAME}:39092,EXTERNAL://${PUBLIC_IP}:39093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_DELETE_RETENTION_MS: 1000
      KAFKA_ERRORS_TOLERANCE: "all"
      KAFKA_ERRORS_DEADLETTERQUEUE_TOPIC_NAME: "dead"
