// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Codegen.Avro.Models
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class MessageModel : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"MessageModel\",\"namespace\":\"Codegen.Avro.Models\",\"fields\"" +
				":[{\"name\":\"Title\",\"type\":\"string\"},{\"name\":\"Message\",\"type\":\"string\"},{\"name\":\"T" +
				"ransactionTs\",\"type\":\"string\"},{\"name\":\"CorrelationId\",\"type\":\"string\"}]}");
		private string _Title;
		private string _Message;
		private string _TransactionTs;
		private string _CorrelationId;
		public virtual Schema Schema
		{
			get
			{
				return MessageModel._SCHEMA;
			}
		}
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				this._Title = value;
			}
		}
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				this._Message = value;
			}
		}
		public string TransactionTs
		{
			get
			{
				return this._TransactionTs;
			}
			set
			{
				this._TransactionTs = value;
			}
		}
		public string CorrelationId
		{
			get
			{
				return this._CorrelationId;
			}
			set
			{
				this._CorrelationId = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Title;
			case 1: return this.Message;
			case 2: return this.TransactionTs;
			case 3: return this.CorrelationId;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Title = (System.String)fieldValue; break;
			case 1: this.Message = (System.String)fieldValue; break;
			case 2: this.TransactionTs = (System.String)fieldValue; break;
			case 3: this.CorrelationId = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
