// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Kafka.Communication.Models
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class CreatePaymentResponse : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""CreatePaymentResponse"",""namespace"":""Kafka.Communication.Models"",""fields"":[{""name"":""CorrelationId"",""doc"":""CorrelationId for this request"",""type"":""string""},{""name"":""OrderId"",""doc"":""Order Id for this order"",""type"":""string""},{""name"":""PaymentInformation"",""doc"":""Get Payment Information"",""type"":{""type"":""record"",""name"":""PaymentInformation"",""namespace"":""Kafka.Communication.Models"",""fields"":[{""name"":""PaymentId"",""type"":""string""},{""name"":""PaymentStatus"",""type"":""string""},{""name"":""PaymentAmount"",""type"":""double""}]}}]}");
		/// <summary>
		/// CorrelationId for this request
		/// </summary>
		private string _CorrelationId;
		/// <summary>
		/// Order Id for this order
		/// </summary>
		private string _OrderId;
		/// <summary>
		/// Get Payment Information
		/// </summary>
		private Kafka.Communication.Models.PaymentInformation _PaymentInformation;
		public virtual Schema Schema
		{
			get
			{
				return CreatePaymentResponse._SCHEMA;
			}
		}
		/// <summary>
		/// CorrelationId for this request
		/// </summary>
		public string CorrelationId
		{
			get
			{
				return this._CorrelationId;
			}
			set
			{
				this._CorrelationId = value;
			}
		}
		/// <summary>
		/// Order Id for this order
		/// </summary>
		public string OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				this._OrderId = value;
			}
		}
		/// <summary>
		/// Get Payment Information
		/// </summary>
		public Kafka.Communication.Models.PaymentInformation PaymentInformation
		{
			get
			{
				return this._PaymentInformation;
			}
			set
			{
				this._PaymentInformation = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.CorrelationId;
			case 1: return this.OrderId;
			case 2: return this.PaymentInformation;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.CorrelationId = (System.String)fieldValue; break;
			case 1: this.OrderId = (System.String)fieldValue; break;
			case 2: this.PaymentInformation = (Kafka.Communication.Models.PaymentInformation)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
