// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentMicroservice.Infrastructure;

namespace PaymentMicroservice.Migrations
{
    [DbContext(typeof(PaymentDBContext))]
    [Migration("20191223165407_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PaymentMicroservice.Domain.AggregateModel.PaymentEntity", b =>
                {
                    b.Property<string>("PaymentId")
                        .HasColumnName("payment_id")
                        .HasColumnType("varchar(64)");

                    b.Property<double>("AmountPayable")
                        .HasColumnName("amount_payable")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedTs")
                        .HasColumnName("created_ts")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnName("order_id")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnName("payment_status")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnName("username")
                        .HasColumnType("varchar(50)");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("tbl_payments");
                });
#pragma warning restore 612, 618
        }
    }
}
