---
version: '2.1'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: 0.0.0.0:12888:13888;0.0.0.0:22888:23888;0.0.0.0:32888:33888;${ZK_O_HOSTNAME}:42888:43888;${ZK_O_HOSTNAME}:52888:53888
    network_mode: host
  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: 0.0.0.0:12888:13888;0.0.0.0:22888:23888;0.0.0.0:32888:33888;${ZK_O_HOSTNAME}:42888:43888;${ZK_O_HOSTNAME}:52888:53888
    network_mode: host
  zookeeper-3:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: 0.0.0.0:12888:13888;0.0.0.0:22888:23888;0.0.0.0:32888:33888;${ZK_O_HOSTNAME}:42888:43888;${ZK_O_HOSTNAME}:52888:53888
    network_mode: host
