---
version: '3.7'
services:
  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    network_mode: host
    restart: unless-stopped
    environment:
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:19092,PLAINTEXT://kafka1:29092,PLAINTEXT://kafka1:39092,PLAINTEXT://kafka2:49092,PLAINTEXT://kafka2:59092
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: "3"
      SCHEMA_REGISTRY_HOST_NAME: "kafka-schema-registry"
  rest-proxy:
    image: confluentinc/cp-kafka-rest:latest
    network_mode: host
    restart: unless-stopped
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: 'kafka1:19092,kafka1:29092,kafka1:39092,kafka2:49092,kafka3:59092'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://kafka2:8081'
  lenses:
    image: lensesio/lenses
    network_mode: host
    environment:
      LENSES_PORT: 9991
      LENSES_KAFKA_BROKERS: "PLAINTEXT://kafka1:19092,PLAINTEXT://kafka1:29092,PLAINTEXT://kafka1:39092,PLAINTEXT://kafka2:49092,PLAINTEXT://kafka2:59092"
      LENSES_SCHEMA_REGISTRY_URLS: |
        [
          {url:"http://kafka2:8081"}
        ]
      LENSES_ZOOKEEPER_HOSTS: |
        [
          {url:"kafka1:12181"},
          {url:"kafka1:22181"},
          {url:"kafka1:32181"},
          {url:"kafka2:42181"},
          {url:"kafka2:52181"}
        ]
      LENSES_SECURITY_USER: kafka
      LENSES_SECURITY_PASSWORD: kafka-workshop
    network_mode: host