// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Kafka.Communication.Models
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class ItemCost : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"ItemCost\",\"namespace\":\"Kafka.Communication.Models\",\"fiel" +
				"ds\":[{\"name\":\"ItemId\",\"type\":\"string\"},{\"name\":\"ItemName\",\"type\":\"string\"},{\"nam" +
				"e\":\"CostPrice\",\"type\":\"double\"}]}");
		private string _ItemId;
		private string _ItemName;
		private double _CostPrice;
		public virtual Schema Schema
		{
			get
			{
				return ItemCost._SCHEMA;
			}
		}
		public string ItemId
		{
			get
			{
				return this._ItemId;
			}
			set
			{
				this._ItemId = value;
			}
		}
		public string ItemName
		{
			get
			{
				return this._ItemName;
			}
			set
			{
				this._ItemName = value;
			}
		}
		public double CostPrice
		{
			get
			{
				return this._CostPrice;
			}
			set
			{
				this._CostPrice = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ItemId;
			case 1: return this.ItemName;
			case 2: return this.CostPrice;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ItemId = (System.String)fieldValue; break;
			case 1: this.ItemName = (System.String)fieldValue; break;
			case 2: this.CostPrice = (System.Double)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
